### PR TITLE
First milestone: Basic file structure and Heroku deploy

### PR DESCRIPTION
**Pull request by Abhigyan001**
1. Set-up a basic file structure.
2. Prepare for Heroku deployment.
3. Set up linter files.

### CODE REVIEW

**Review by mikenath223 — APPROVED** [review]
### CONGRATULATIONS  👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**


Don't forget to fill the project completion form👍
Good luck with the next project.

HAPPY CODING👨‍💻

**Comment by mikenath223** [comment]
I reviewed changes made on this commit title: **Edit Readme file to include live link**. Further changes were made after the student submitted a review request which didn't show up until after my review.

**Comment by Abhigyan001** [comment]
> I reviewed changes made on this commit title: **Edit Readme file to include live link**. Further changes were made after the student submitted a review request which didn't show up until after my review.

Heroku sent an error after I installed big.js. I have fixed it now.

**Comment by Abhigyan001** [comment]
Merging on successful Heroku deployment.

**Pull request merged**
